name: Code analysis

on:
  push

jobs:
  code-analysis:
    name: Check code and memory leaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Getting dependencies
        run: sudo apt-get install cppcheck valgrind

      - name: Running static code analysis
        run: |
          cppcheck --enable=warning --error-exitcode=1 sources/*.cpp
          cppcheck --enable=performance,style --output-file=cppcheck_report.txt sources/*.cpp

      - name: Creating cppcheck artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cppcheck_report
          path: cppcheck_report.txt

      - name: Compiling the code
        run: g++ -Wall -std=c++17 sources/*.cpp -o a.out -g

      - name: Checking for memory leaks
        run: valgrind --leak-check=full --error-exitcode=1 ./a.out json_files/scenario1.json
