name: Code analysis

on:
  push

jobs:
  code-analysis:
    name: Check code and memory leaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Getting dependencies
        run: sudo apt-get install cppcheck valgrind

      - name: Running static code analysis
        run: make static-code-analysis

      - name: Creating cppcheck artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cppcheck_report
          path: cppcheck_report.txt

      - name: Checking for memory leaks
        run: make memory-leak-test
