name: I/O tests

on:
  push

jobs:
  io-tests:
    name: Run i/o tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Running i/o tests
        run: make io-test
