name: GitHub pages deploy

on:
  push:
    branches:
      - makefile
      - master
      - gh-pages

jobs:
  deploy:
    name: Deploy to GitHub pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Getting dependencies
        run: sudo apt-get install doxygen graphviz

      - name: Creating documentation page
        run: make documentation

      - name: Pushing git subdirectory as branch
        uses: s0/git-publish-subdir-action@v2.4.0
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: DOCS/html
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
