name: Unit test

on:
  push

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Getting dependencies

        run: |
          sudo apt-get install libgtest-dev cmake
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo ln -st /usr/lib/ /usr/src/gtest/libgtest.a
          sudo ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a

      - name: Running unit tests
        run: make unit-test
